INSERT INTO [ChurnDB].[dbo].[ChurnData]
SELECT
    Customer_ID,
    Gender,
    Age,
    Married,
    State,
    Number_of_Referrals,
    Tenure_in_Months,
    ISNULL(Value_Deal, 'None') AS Value_Deal,
    ISNULL(CAST(Phone_Service AS bit), 0) AS Phone_Service,
    ISNULL(CAST(Multiple_Lines AS bit), 0) AS Multiple_Lines,
    Internet_Service,
    ISNULL(Internet_Type, 'None') AS Internet_Type,
    ISNULL(CAST(Online_Security AS bit), 0) AS Online_Security,
    ISNULL(CAST(Online_Backup AS bit), 0) AS Online_Backup,
    ISNULL(CAST(Device_Protection_Plan AS bit), 0) AS Device_Protection_Plan,
    ISNULL(CAST(Premium_Support AS bit), 0) AS Premium_Support,
    ISNULL(CAST(Streaming_TV AS bit), 0) AS Streaming_TV,
    ISNULL(CAST(Streaming_Movies AS bit), 0) AS Streaming_Movies,
    ISNULL(CAST(Streaming_Music AS bit), 0) AS Streaming_Music,
    ISNULL(CAST(Unlimited_Data AS bit), 0) AS Unlimited_Data,
    Contract,
    ISNULL(CAST(Paperless_Billing AS bit), 0) AS Paperless_Billing,
    Payment_Method,
    Monthly_Charge,
    Total_Charges,
    Total_Refunds,
    Total_Extra_Data_Charges,
    Total_Long_Distance_Charges,
    Total_Revenue,
    Customer_Status,
    ISNULL(Churn_Category, 'Others') AS Churn_Category,
    ISNULL(Churn_Reason, 'Others') AS Churn_Reason
FROM [ChurnDB].[dbo].[Customer_Data];
